[package]
name = "tetris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.5"
game-loop = "0.9.1"
rand = "0.6.0"
keyboard_query = "0.1.0"
